from __future__ import annotations
import hashlib,json,re,zipfile
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; FREEZE=Path(__file__).resolve().parent; SUITES=FREEZE/'suites'
MEMBERS={
'LI_LINGHAO':ROOT/'Part3_LI_LINGHAO/d5_live_submissions/LI_LINGHAO/r1.1/D5_RETURN_LI_LINGHAO.zip',
'ZHOU_SIHAN':ROOT/'Part3_LI_LINGHAO/d5_live_submissions/ZHOU_SIHAN/r1.1/D5_RETURN_ZHOU_SIHAN.zip',
'CHEN_MINGSONG':ROOT/'Part3_LI_LINGHAO/d5_live_submissions/CHEN_MINGSONG/r1.1/D5_RETURN_CHEN_MINGSONG.zip',
'LU_XINZE':ROOT/'Part2_LU_XINZE/D5_RETURN_LU_XINZE.zip',
'WANG_YI':ROOT/'Part3_LI_LINGHAO/d5_live_submissions/WANG_YI/r1.1/D5_RETURN_WANG_YI.zip',
'DAI_MINFEI':ROOT/'Part4_DAI_MINFEI/DAI_MINFEI_GITHUB_UPLOAD/D5_RETURN_DAI_MINFEI.zip'}
def sha(b): return hashlib.sha256(b).hexdigest()
def readj(z,n): return json.loads(z.read(n).decode('utf-8-sig'))
def main():
 now=datetime.now(timezone.utc).isoformat(); manifest={'generated_at':now,'judge_model':'openai/gpt-4.1-mini','contract_revision':'d5-live-1.1','hash_binding':'package_sha256 is SHA-256(package_manifest.json), not ZIP container','members':{}}
 checks={'generated_at':now,'members':{}}; report_rows=[]; total_cost=0
 for member,zpath in MEMBERS.items():
  with zipfile.ZipFile(zpath) as z:
   assert z.testzip() is None
   names=set(z.namelist()); rows=readj(z,'suite/results.json'); meta=readj(z,'suite/metadata.json'); summary=readj(z,'suite/summary.json'); assignment=readj(z,'assignment.json'); manifest_bytes=z.read('package_manifest.json'); preflight=z.read('suite/preflight.json'); embrel=readj(z,'suite/release.json'); ext=json.loads((zpath.parent/'release.json').read_text())
   pairs={(r['case_id'],int(r['trial'])) for r in rows}; runs={r['record'].get('run_id') for r in rows}; template=readj(z,'suite/review_template.json'); reviewable={(x['case_id'],int(x['trial'])) for x in template}
   jdir=next((SUITES/member/'suite').glob('llm_judge_*')); js=json.loads((jdir/'summary.json').read_text()); jr=json.loads((jdir/'results.json').read_text()); by={(x['case_id'],int(x['trial'])):x for x in jr}
   jp=sum(by.get(k,{}).get('judgement')=='pass' for k in reviewable); jf=sum(by.get(k,{}).get('judgement')=='fail' for k in reviewable); ju=sum(by.get(k,{}).get('judgement')=='pending' for k in reviewable); overall=sum(bool(r['code_passed']) and by.get((r['case_id'],int(r['trial'])),{}).get('judgement')=='pass' for r in rows); cost=float(js.get('judge_cost_usd') or 0); total_cost+=cost
   binding={'manifest_sha256':sha(manifest_bytes),'external_release_package_sha256':ext.get('package_sha256'),'embedded_release_package_sha256':embrel.get('package_sha256'),'preflight_sha256':sha(preflight),'external_release_preflight_sha256':ext.get('preflight_sha256'),'embedded_release_preflight_sha256':embrel.get('preflight_sha256'),'package_binding_ok':ext.get('package_sha256')==sha(manifest_bytes)==embrel.get('package_sha256'),'preflight_binding_ok':ext.get('preflight_sha256')==sha(preflight)==embrel.get('preflight_sha256'),'zip_container_sha256':sha(zpath.read_bytes())}
   integ={'zip_readable':True,'rows_75':len(rows)==75,'unique_case_trial_pairs_75':len(pairs)==75,'unique_cases_45':len({r['case_id'] for r in rows})==45,'unique_run_ids_75':len(runs)==75,'all_transcripts':all(f"suite/{r['record']['run_id']}/transcript.txt" in names for r in rows),'all_decision_logs':all(f"suite/{r['record']['run_id']}/decisions.jsonl" in names for r in rows),'live_backend':meta.get('backend')=='live','contract_revision_ok':meta.get('contract_revision')=='d5-live-1.1','assignment_matches_metadata':meta.get('model')==assignment.get('model') and meta.get('prompt_version')==assignment.get('version'),'no_api_key_pattern':not any(re.search(rb'sk-or-v1-[A-Za-z0-9]{20,}',z.read(n)) for n in names),**binding,'judge_complete':js.get('judge_calls_error')==0 and js.get('judge_calls_pending')==0 and js.get('judge_calls_completed')==len(reviewable)}
   checks['members'][member]=integ; manifest['members'][member]={'source_zip':str(zpath.relative_to(ROOT)),'source_zip_sha256':binding['zip_container_sha256'],'package_manifest_sha256':binding['manifest_sha256'],'preflight_sha256':binding['preflight_sha256'],'model':meta.get('model'),'prompt_version':meta.get('prompt_version'),'trials':len(rows),'cases':len({r['case_id'] for r in rows}),'code_passed':summary['code_passed'],'execution_errors':summary['execution_errors'],'reviewable_trials':len(reviewable),'judge':{'judge_dir':str(jdir.relative_to(FREEZE)),'judge_model':js.get('judge_model'),'calls_completed':js.get('judge_calls_completed'),'calls_error':js.get('judge_calls_error'),'calls_pending':js.get('judge_calls_pending'),'judge_cost_usd':cost,'reviewable_trials':len(reviewable),'judge_pass_trials':jp,'judge_fail_trials':jf,'judge_uncertain_trials':ju,'criteria_pass':js.get('judge_criteria',{}).get('pass',0),'criteria_fail':js.get('judge_criteria',{}).get('fail',0),'criteria_uncertain':js.get('judge_criteria',{}).get('uncertain',0)},'overall_passed':overall,'integrity_pass':all(integ.values())}
   report_rows.append((member,meta,summary,len(reviewable),jp,jf,ju,overall,cost))
 (FREEZE/'D5_EVIDENCE_MANIFEST.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False)+'\n'); (FREEZE/'D5_FREEZE_CHECKS.json').write_text(json.dumps(checks,indent=2,ensure_ascii=False)+'\n')
 tc=sum(int(x[2]['code_passed']) for x in report_rows); te=sum(int(x[2]['execution_errors']) for x in report_rows); tr=sum(x[3] for x in report_rows); to=sum(x[7] for x in report_rows)
 lines=['# Team D5 Final Freeze Report','',f'Generated: {now}','Frozen contract: `d5-live-1.1`','', '## Decision','',f'All six members have complete 45-case/75-trial live batteries. All {tr} reviewable completed trials received the common independent `openai/gpt-4.1-mini` judgement with zero judge transport errors or pending calls. Execution failures remain in the original 75-trial denominator and have no fabricated judgement.','', 'The release bindings are valid. `package_sha256` is the package-manifest digest defined by the frozen runner; ZIP container hashes are recorded only as transport fingerprints. ZHOU_SIHAN prompt version `v1` is an intentional paired configuration and is preserved.','', '## Member results','', '| Member | Model | Prompt | Code pass | Execution errors | Reviewable | Judge pass/fail/uncertain | Overall pass | Judge cost |','|---|---|---:|---:|---:|---:|---:|---:|---:|']
 for m,meta,s,r,jp,jf,ju,o,c in report_rows: lines.append(f'| {m} | `{meta.get("model")}` | `{meta.get("prompt_version")}` | {s["code_passed"]}/75 | {s["execution_errors"]} | {r} | {jp}/{jf}/{ju} | {o}/75 | ${c:.6f} |')
 lines += ['',f'Team totals: code checks **{tc}/450**, execution errors **{te}/450**, reviewable trials **{tr}/450**, overall code-and-judge pass **{to}/450**, judge API usage **${total_cost:.6f}**.','', '## Interpretation','', '- Overall pass means both deterministic code check and independent judge pass.', '- The execution failures are not judged and remain in the denominator.', '- CHEN_MINGSONG and LU_XINZE model/protocol failures are retained; no score-chasing rerun was performed.', '- WANG_YI has three judge-failed completed trials; one also fails deterministic code checks. LI_LINGHAO has one uncertain judgement and it is not counted as a pass.','', '## Evidence','', '- `HASH_AND_VERSION_BINDING.md` records the hash semantics and ZHOU version decision.', '- `D5_EVIDENCE_MANIFEST.json` records source ZIP, manifest, preflight, judge and transport hashes.', '- `D5_FREEZE_CHECKS.json` records all integrity assertions.', '- Per-member extracted suites and judge call evidence are under `suites/<MEMBER>/suite/`.','']
 (FREEZE/'D5_FINAL_REPORT.md').write_text('\n'.join(lines)); print(json.dumps({'reviewable':tr,'judge_cost':total_cost,'overall':to,'all_integrity':all(all(v.values()) for v in checks['members'].values())},indent=2))
if __name__=='__main__': main()
