#!/usr/bin/env python3
"""Build the English report and static figures from measured results.

Authoring dependencies only: reportlab, matplotlib. The assessed runtime needs neither.
"""
import json,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,Image,PageBreak,KeepTogether
from xml.sax.saxutils import escape


def main():
    data=json.loads((ROOT/'results/cost_model.json').read_text());models=data['models'];best=next(x for x in models if x['model']==data['recommended'] and x['variant']=='v2');cheap=next(x for x in models if x['model']==data['cheapest_token_model'] and x['variant']=='v2');gem=next(x for x in models if x['model'].startswith('google') and x['variant']=='v2');old=next(x for x in models if x['variant']=='v1');lv=data['levers'];d7=json.loads((ROOT/'results/d7_failures.json').read_text());loop=d7['loop'];it=d7['interface'];short=lambda s:s.split('/')[-1]
    sections=[('1. Why an agent',[
        'Problem A concerns first response, not autonomous adjudication or payment. The insurer fixes three outcomes: approve in principle, request a named document, or escalate on one trigger. Mixed payable and excluded lines still produce one approval-in-principle record. Our five pre-build commitments require traceable facts, exact outcomes, one gated write, explicit uncertainty and measured economics. Wang Yi’s original D0 precedes the member agent implementation in Git; integration commitments were also committed before the integrated engine.',
        'The assignment selects rung 7, but a fixed branching workflow could implement these finite rules. A single call cannot independently verify records. Chains and routing could enumerate branches; parallelisation only groups independent checks. Orchestrator-workers would add coordination, while evaluator-optimiser could revise a proposal but still needs retrieved evidence. Our single ReAct planner instead chooses eligible tools from observations. That buys adaptive retrieval, not a proof that workflows are impossible. A stable production protocol might favour the cheaper workflow.',
        'The workflow test asks who selects the next step, whether length varies, what can be tested and how cost is bounded. The live model selects its trajectory; one-line, multi-line, authorisation and early-escalation cases produce different lengths. We test outcomes and controls rather than claiming exhaustive path coverage. Claims, policies, procedures, documents and authorisations provide objective local ground truth within milliseconds. Without those signals, we would use a workflow with a human gate. The governance cliff is the first write: issue_decision_letter appends a local record only after validation and confirmation.',
        f"Using the final Gemini measurement, P={gem['passing']}/64={gem['pass_rate']:.4f} and median T={gem['median_turns']:g}, implied s=P^(1/T)={gem['implied_step_reliability']:.4f}. Holding s fixed predicts {gem['implied_step_reliability']**2:.1%} at two turns and {gem['implied_step_reliability']**8:.1%} at eight. This is diagnostic, not an independent-step law. Failure grouping most often points to the period after policy retrieval; malformed escalation proposals and repetition, rather than incorrect policy facts, make interface quality the immediate target."
    ]),('2. The tool layer',[
        'We consolidated the member designs into six bounded JSON tools: claim, policy, coverage, preauthorisation, hospital and decision. Member resolution moved inside policy lookup; duplicate metadata moved inside claim retrieval; document requirements moved inside coverage. This follows the four moves before adding a tool: widen inputs, return related facts, use ordinary code, then justify a separate conditional tool. Hospital status earns its place because a non-panel result must be recorded, even though it does not change routing. Every tool has the full six-field contract and a three-question justification in the repository.',
        'Two constraints make mistakes impossible at the boundary. Claim-scoped inputs reject cross-member substitutions and derive service date and amount from records; models cannot omit those facts to bypass checks. Procedure membership and prior coverage evidence prevent unrelated or unnecessary authorisation calls. Decimal validation, exact line checks and immutable confirmation payloads further protect the writer. Default confirm never auto-approves in the core; evaluation explicitly supplies a simulated operator. No real letter, email, payment or interface is built.',
        f"The dependency rule is claim, then policy, then independent coverage checks and hospital, then required authorisations, then a lone write. An observed policy ID is never hardcoded to manufacture parallelism. Across 64 scripted trials, sequential median/max turns were 5/9 versus 4/5 with grouping; both passed 64/64. Estimated input fell from {lv['sequential']['tokens_in']:,} to {lv['parallel']['tokens_in']:,}, or {lv['input_reduction_fraction']:.1%}. Local reads execute deterministically; the benefit is fewer model turns. Early exits avoid unnecessary coverage, whereas batching can still perform a read that later proves unnecessary.",
        f"The preauthorisation rewrite preserves IDs, dates and all candidates while removing explanation repeated in observations. Mean estimated return size fell from {lv['preauth_observation_v1_mean_estimated_tokens']:.1f} to {lv['preauth_observation_v2_mean_estimated_tokens']:.1f} tokens. On Gemini alone, v1 passed {old['passing']}/64 and v2 {gem['passing']}/64; negative performance stayed {gem['negative_passing']}/36. This small difference is not persuasive causal evidence of better model judgement. Both safety variants pass the scripted guardrail checks. Fewer tools also did not guarantee a smaller prefix: complete contracts are a real cost."
    ]),('3. What the evidence showed',[
        'We preserved all 15 supplied records and labels, added 25 labelled cases with explicit member/AI provenance, and checked deterministic regeneration. The final set has 28 ordinary cases and 12 negatives: one trial for each ordinary case and three for each negative, giving 64 trials per configuration. Labels were derived independently from routing rules. Each trial has isolated state. Code checks cover outcome, trigger, named missing item, amounts, line dispositions, evidence and gate, not merely a favourable keyword.',
        f"The official battery contains five distinct families at two price tiers plus one Gemini v1 comparison: 384 live trials on a frozen source/data hash. {short(best['model'])} led with {best['passing']}/64 ({best['pass_rate']:.1%}) and {best['negative_passing']}/36 negatives. Llama passed 48/64; Gemini and GPT-4o-mini passed 26/64 and 27/64. Cheap tokens often became failed tasks. Repeated actions, wrong write shapes and invalid escalation fields dominated failures; they were retained, not rerun until favourable. A transport timeout also remains a failure with incomplete returned usage.",
        'A preselected six-case subset receives independent reason/evidence judgement: Haiku judges other models, Gemini judges Haiku. The repository preserves the prompt, raw verdict and code/combined counts; an unjudged item cannot pass. An initial judge confused original billed amounts with execution of coverage pricing; we retained its verdicts, clarified that term and rejudged the entire subset without changing agent outputs. Scripted 64/64 proves deterministic integration only. Development first scored 60/64: a role tag with attributes was missed and a benign clinical sentence was overblocked. Their fixes and before traces are documented. Pilot cases informed development, so this is not a held-out generalisation study. All live jobs used the requested shared key centrally; that does not establish individual member execution.'
    ]),('4. What it costs',[
        'We reuse Class 5’s three layers: list-price input/output cost; expected fallback (1-P) times US$7.60, from US$38/hour for twelve minutes; and fixed monthly cost. At 8,000 claims, monthly cost is 8,000 times the first two layers plus fixed cost. Our US$80 fixed allowance is an explicit assumption: storage 5, infrastructure 10, monitoring 10, evaluation refresh 5 and maintenance 50. It is not the course API bill.',
        f"For {short(best['model'])}, measured tokens imply US${best['variable_usd']:.5f} variable cost and US${best['fallback_usd']:.4f} expected fallback per task, or US${best['monthly_usd']:,.2f} monthly including fixed cost. It is the lowest measured fallback-inclusive option despite higher token prices. For the cheapest token model, {short(cheap['model'])}, break-even success against the expensive option is {data['cheap_break_even_success']:.2%}; its measured {data['cheap_actual_success']:.2%} falls short. The sensitivity figure varies success by ten percentage points, clipped to zero and one; the recommendation is less secure when model uncertainty and production case mix are considered.",
        f"The ledger measures all four levers. Tool-definition estimates are {lv['tool_prefix_before_estimated_tokens']} before and {lv['tool_prefix_after_estimated_tokens']} after complete contracts, so consolidation did not save prefix tokens. Grouping reduced repeated input by {lv['input_reduction_fraction']:.1%}; smaller observations reduced later context; success rate dominated economics because fallback dwarfs tokens. We use actual API token counts for live baseline pricing and report provider charges separately. No caching discount is assumed, and no caching experiment is claimed. Hidden reasoning, where returned in usage, remains billed output.",
        'We ship a ten-turn cap, 60,000-token ceiling, dollar stopping threshold with in-flight reserve, and the provider’s US$10 lifetime key ceiling, stricter than US$10 in any month without top-ups. Correct business escalations count as successful tasks, not model errors. Their ordinary human handling, confirmation labour and an unrepresentative trial-weighted case mix are additional production considerations. Our cost recommendation is an experimental comparison, not a deployment business case.'
    ]),('5. The two failures',[
        f"Both experiments remove one component from the final working engine. Under the identical repeating get_claim fault, dedup stops at {loop['normal']['turns']} turns; deleting it consumes {loop['ablated']['turns']} until the step cap. Estimated input rises from {loop['normal']['tokens_in']:,} to {loop['ablated']['tokens_in']:,}; cost from US${loop['normal']['cost_usd']:.5f} to US${loop['ablated']['cost_usd']:.5f}. Both fail the business task; restoration restores containment, not magical completion. Dedup detects repetition before the step cap, while token/dollar caps bound different resources. Ordinary full-set correctness stays 64/64.",
        'Removing only preauthorisation validity projection makes an expired candidate appear usable, causing an approval proposal for CLM-8894. The unchanged independent writer rejects it; normal and restored runs correctly request current authorisation. This is a contained interface failure, not an unsafe write. Fixing the interface preserves objective validity; prompt wording cannot repair false tool semantics. Loop memory belongs in code, not another tool or a plea to remember. The complete before/after traces, counts, costs and pass status are reproducible without a key.'
    ]),('6. What we would not deploy',[
        'We would not deploy this unchanged. Known-pattern injection screening is incomplete, records are synthetic, outcomes are correlated, and 64 trials do not establish production reliability. The writer validates structured facts, while explanation quality still needs judgement. A second runtime reviewing agent could catch some omissions but adds calls, correlated errors and another attack surface; it should never introduce a second writer. We used a separate judge only as an evaluation instrument and logged its cost. A deterministic workflow deserves a production comparison. Members must still confirm contributions and collective appraisal, record all six speakers, and complete publication/submission steps.'
    ])]
    prose='\n\n'.join(p for _,paras in sections for p in paras)
    words=len(re.findall(r"\b[\w’-]+\b",prose))
    if words>2000: raise SystemExit(f'Report prose too long: {words}')
    md=['# Group-6 | Problem A','',f'PE6201 A2 — Applied AI System. Measured 15 September 2026. Prose word count: {words}.','']
    for title,paras in sections:md+=['## '+title,'']+['\n\n'.join(paras),'']
    md+=['## References and evidence','', '- PE6201 A2 brief and FAQ, D0–D7 and Appendix A.','- PE6201 Class 4 agent build and Class 5 cost-to-serve notebook: loop, three-layer formulas and break-even method.','- Original member sources and AI assistance: CONTRIBUTIONS.md and IMPROVEMENTS.md.','- OpenRouter model catalog and returned usage, captured in results/model_catalog.json and results/live/.','- Independent judgement prompt/results and offline guardrail/failure traces in results/.']
    (ROOT/'docs/REPORT.md').write_text('\n'.join(md)+'\n')
    out=ROOT/'output/pdf';out.mkdir(parents=True,exist_ok=True);fig=ROOT/'output/figures';fig.mkdir(parents=True,exist_ok=True)
    plt.rcParams.update({'font.family':'DejaVu Sans','font.size':10,'axes.spines.top':False,'axes.spines.right':False})
    v2=[x for x in models if x['variant']=='v2'];names=[short(x['model']).replace('qwen3-30b-a3b-instruct-2507','Qwen3 30B').replace('llama-3.3-70b-instruct','Llama 3.3 70B') for x in v2]
    f,ax=plt.subplots(figsize=(9,3.5));bars=ax.barh(names,[x['pass_rate']*100 for x in v2],color=['#367e9b']*4+['#159980'])
    for bar,x in zip(bars,v2):ax.text(x['pass_rate']*100+1,bar.get_y()+bar.get_height()/2,f"{x['passing']}/64",va='center')
    ax.set_xlim(0,104);ax.set_xlabel('Strong code-check pass rate (%)');ax.invert_yaxis();ax.set_title('Live performance varies despite identical tools and guards',loc='left',weight='bold');f.tight_layout();f.savefig(fig/'model_performance.png',dpi=180);plt.close(f)
    f,ax=plt.subplots(figsize=(9,3.5))
    for x,n in zip(v2,names):
        points=x['sensitivity'];ax.plot([p['success_rate']*100 for p in points],[p['cost_per_task_usd'] for p in points],marker='o',label=n)
    ax.set_xlabel('Success rate: measured value ±10 percentage points');ax.set_ylabel('US$ per task including error fallback');ax.legend(fontsize=8,loc='upper right');ax.set_title('Fallback cost dominates token price',loc='left',weight='bold');f.tight_layout();f.savefig(fig/'cost_sensitivity.png',dpi=180);plt.close(f)
    styles=getSampleStyleSheet();styles.add(ParagraphStyle(name='BodyA2',fontName='Helvetica',fontSize=9.7,leading=14,spaceAfter=8,textColor=colors.HexColor('#233347')));styles.add(ParagraphStyle(name='HeadingA2',fontName='Helvetica-Bold',fontSize=13,leading=17,spaceBefore=13,spaceAfter=8,textColor=colors.HexColor('#164863'),keepWithNext=True));styles.add(ParagraphStyle(name='SmallA2',fontName='Helvetica',fontSize=8,leading=11,spaceAfter=5,textColor=colors.HexColor('#496171')))
    story=[Paragraph('GROUP-6 / PROBLEM A',styles['HeadingA2']),Paragraph('Health-insurance claim<br/>first response',ParagraphStyle('TitleA2',fontName='Helvetica-Bold',fontSize=28,leading=33,textColor=colors.HexColor('#15334b'),spaceAfter=12)),Paragraph(f'PE6201 · Assessment 2 · 15 September 2026<br/>A measured single-agent system, with an auditable local write<br/>Report prose: {words} words; tables, figures and references excluded.',styles['SmallA2']),Spacer(1,8)]
    for title,paras in sections:
        story.append(Paragraph(escape(title),styles['HeadingA2']))
        for para in paras:story.append(Paragraph(escape(para),styles['BodyA2']))
    story.append(PageBreak());story.append(Paragraph('Evidence tables and figures',styles['HeadingA2']))
    table=[['Model / version','Pass','Negative','Turns\nmedian/max','Token US$\nper task','Total US$\nper task']]
    for x in models:table.append([short(x['model']).replace('qwen3-30b-a3b-instruct-2507','Qwen3 30B').replace('llama-3.3-70b-instruct','Llama 3.3 70B')+' '+x['variant'],f"{x['passing']}/64",f"{x['negative_passing']}/36",f"{x['median_turns']:g}/{x['worst_turns']}",f"{x['variable_usd']:.5f}",f"{x['cost_per_task_usd']:.3f}"])
    t=Table(table,colWidths=[172,43,52,62,70,70],repeatRows=1);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#163c54')),('TEXTCOLOR',(0,0),(-1,0),colors.white),('FONTNAME',(0,0),(-1,0),'Helvetica-Bold'),('FONTSIZE',(0,0),(-1,-1),8),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.HexColor('#edf4f6'),colors.white]),('LINEBELOW',(0,-1),(-1,-1),.5,colors.HexColor('#b6c7ce'))]));story+=[t,Spacer(1,10),Paragraph('Each row is 64 trials on 40 cases; negative cases are repeated three times. No pilot trials are included. Total cost adds expected error fallback, excluding fixed monthly overhead. Figures are fixture-specific comparisons, not production guarantees.',styles['SmallA2']),Image(str(fig/'model_performance.png'),width=500,height=194),Spacer(1,8),Image(str(fig/'cost_sensitivity.png'),width=500,height=194)]
    story.append(Paragraph('References and reproducibility',styles['HeadingA2']))
    story.append(Paragraph('PE6201 A2 brief/FAQ and Appendix A; Class 4 agent-build and Class 5 cost-to-serve notebooks. Member and AI provenance: CONTRIBUTIONS.md. Raw evidence: results/live, results/judgement, results/d7_failures.json. Exact tool contracts and changes: docs/TOOL_CONTRACTS.md and IMPROVEMENTS.md. Reproduce offline with python3 scripts/reproduce.py. Pricing source: OpenRouter catalog snapshot, 15 September 2026.',styles['SmallA2']))
    def page(canvas,doc):
        canvas.setStrokeColor(colors.HexColor('#159980'));canvas.setLineWidth(1);canvas.line(43,37,552,37);canvas.setFont('Helvetica',8);canvas.setFillColor(colors.HexColor('#496171'));canvas.drawString(43,24,'PE6201 A2 | Group-6 | Problem A');canvas.drawRightString(552,24,str(doc.page))
    SimpleDocTemplate(str(out/'PE6201_A2_Group-6_Report.pdf'),pagesize=(595.28,841.89),rightMargin=43,leftMargin=43,topMargin=39,bottomMargin=49,title='Group-6 Problem A: Health-insurance claim first response',author='Group-6; AI-assisted integration disclosed').build(story,onFirstPage=page,onLaterPages=page)
    (ROOT/'results/report_validation.json').write_text(json.dumps({'prose_words':words,'limit':2000,'source':'docs/REPORT.md','pdf':'output/pdf/PE6201_A2_Group-6_Report.pdf'},indent=2));print('Report prose words:',words)
if __name__=='__main__':main()
